global using System;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Text.RegularExpressions;
global using TryashtarUtils.Utility;
global using TryashtarUtils.Music;
global using YamlDotNet.RepresentationModel;
global using TagLib;
global using TagLib.Id3v2;
global using File = System.IO.File;
global using Tag = TagLib.Tag;
global using Image = SixLabors.ImageSharp.Image;